name: Cleanup drafts

on:
  schedule:
    - cron: '0 5 * * *'

jobs:
  build:
    runs-on: ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cleanup
        run: |-
          hub release -f "%T (%S) %n" --include-drafts
