name: Cleanup drafts

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:
  # push:
  #   branches:
  #     - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |-
          wget -qO- https://github.com/mislav/hub/releases/download/v2.14.2/hub-linux-amd64-2.14.2.tgz | tar zxf - --strip-components=1 -C /tmp
          export PATH="/tmp/bin:$PATH"
          hub release -f "%T (%S) %n" --include-drafts  | grep " (draft)" | awk '{print $1}' | xargs -t -n1 hub release delete || exit 0
